features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
bookish_copyright_name: 'Emircan ERKUL'
bookish_color_mode: none
